# Generated by Django 5.1.1 on 2026-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('stock_movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_movements',
                'managed': False,
            },
        ),
    ]
